shellEmulator: true

packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/ni': ^28.2.0
  '@base-ui/react': ^1.1.0
  '@cloudflare/workers-types': ^4.20260131.0
  '@fn-sphere/filter': ^1.2.0
  '@hookform/resolvers': ^5.2.2
  '@libsql/client': 0.17.0
  '@orpc/client': ^1.13.4
  '@orpc/openapi': ^1.13.4
  '@orpc/server': ^1.13.4
  '@orpc/tanstack-query': ^1.13.4
  '@orpc/zod': ^1.13.4
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@t3-oss/env-core': ^0.13.10
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/query-async-storage-persister': ^5.90.22
  '@tanstack/react-form': ^1.28.0
  '@tanstack/react-query': ^5.90.20
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-query-persist-client': ^5.90.22
  '@tanstack/react-virtual': ^3.13.18
  '@types/node': ^25.1.0
  '@types/react': ~19.2.10
  '@types/react-dom': ^19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260130.1
  '@vitejs/plugin-react': ^5.1.2
  alchemy: ^0.83.1
  better-auth: ^1.4.18
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  embla-carousel-react: ^8.6.0
  eslint: ^9.39.2
  eslint-config-hyoban: 6.0.0-beta.2
  hono: ^4.11.7
  idb-keyval: ^6.2.2
  input-otp: ^1.4.2
  libsql: 0.5.22
  lint-staged: ^16.2.7
  lucide-react: ^0.563.0
  next-themes: ^0.4.6
  nuqs: ^2.8.7
  react: 19.2.4
  react-day-picker: ^9.13.0
  react-dom: 19.2.4
  react-hook-form: ^7.71.1
  react-resizable-panels: ^4.5.6
  react-router-devtools: ^6.2.0
  react-router-dom: ^7.13.0
  recharts: 3.7.0
  shadcn: ^3.8.0
  simple-git-hooks: ^2.13.1
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsdown: ^0.20.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vaul: ^1.1.2
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.0.5
  wrangler: ^4.61.1
  zod: 4.3.6

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - msw
  - sharp
  - simple-git-hooks
  - workerd
